name=TDAxis12
version=1.0.0
author=Farhan Daemi Mojdehi
maintainer=Farhan Daemi Mojdehi
sentence=reading angle using TDAxis sensor.
paragraph=This library reads TDAxis12 sensor and provides angle data.
category=Sensors
url=https://github.com/yourusername/IRDirection
architectures=*
