name=TSOP
version=1.0.0
author=Farhan Daemi Mojdehi
maintainer=Farhan Daemi Mojdehi
sentence=Detects IR ball direction using multiple TSOP sensors.
paragraph=This library reads multiple IR sensors arranged in a circle and estimates the IR ball direction.
category=Sensors
url=https://github.com/yourusername/IRDirection
architectures=*
