name=LDR RCJ Soccer
version=1.0.0
author=Farhan Daemi Mojdehi
maintainer=Farhan Daemi Mojdehi
sentence=Detects White OutLine on RCJ Soccer Field
paragraph=This library allows you to detect the white outline on the RCJ Soccer field using LDR sensors.
license=MIT
category=Sensors
url=https://github.com/fdmxfarhan/LDR-RCJ-Soccer
architectures=*
